### ISSUE TITLE
can't preview more than 17 spaces

### ISSUE THREAD

**Issue by edono-cjo** [olragon/adjacency-matrix-diagram#1]
Hi! architecture student here. I was doing my matrix diagram with this generator and noticed that the diagram could only preview up to 17 spaces. I'm not sure what to do I already zoomed the page out and it's still the same. hope it gets fixed

![image](https://user-images.githubusercontent.com/120785904/209816675-8c38fb42-7982-4f79-9cdc-6b2e50a0be51.png)

**Comment by olragon** [comment]
Hi @edono-cjo 
I have just deployed the new version, the issue should be fixed now.

![image](https://user-images.githubusercontent.com/47636/209818503-304999fb-a777-4921-a821-b8f9b637b822.png)

**Comment by edono-cjo** [comment]
It's working now thank you very much!! 🙏🙏
