### ISSUE TITLE
Font/color is only gray and cannot be changed

### ISSUE THREAD

**Issue by dillerd1** [olragon/adjacency-matrix-diagram#2]
This is an excellent tool to use for my design classes, but I cannot get the font to change or change the color to be black.  The gray barely is readable and I wish so much to be able to have this in black at the minimum for the room names.

**Comment by olragon** [comment]
Fixed. You can change text colors.
![image](https://github.com/user-attachments/assets/56077c9d-a68d-4597-abaa-6978e4aa4bcf)
